### ISSUE TITLE
Leaked Token

### ISSUE THREAD

**Issue by SourSpoon** [Registeel/DiscordScraperBot#1]
https://github.com/Registeel/DiscordScraperBot/blob/a06911fa1dc31333df28c940ca884186a9308bd8/bot.py#L56

You leaked your token! This gives anyone full access to your bot.
https://discordapp.com/developers/applications/me

Please leverage a config file of some kind and add the config to a gitignore

**Comment by Registeel** [comment]
Oh snap. Thanks for that! Didn't even realize I did it.

**Comment by Registeel** [comment]
I should specify also that I am not an idiot on purpose and my token has been updated.
